CREATE TABLE IF NOT EXISTS BOOKSHELFS (
  ID   SERIAL PRIMARY KEY,
  TITLE VARCHAR(255),
  DESCRIPTION VARCHAR(255)
);

CREATE TABLE IF NOT EXISTS BOOKSHELF_BOOKS (
  ID   SERIAL PRIMARY KEY,
  BOOKSHELF_ID INT,
  BOOK_ID INT
);
